spring:
  application:
    name: eureka-service

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka
