
server:
  port: 8090
spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    user-service:
      path: /api/students/**
      url: http://localhost:8080/students/
      serviceId: user-service
    course-service:
      path: /api/courses/**
      url: http://localhost:8081/courses/
      serviceId: course-service
    exam-service:
      path: /api/exams/**
      url: http://localhost:8082/exams/
      serviceId: exam-service
    answer-service:
      path: /api/answers/**
      url: http://localhost:8083/answers/
      serviceId: answer-service